# Generated by Django 5.2.1 on 2025-06-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sessionmodel_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='home.sessionmodel', verbose_name='Session'),
        ),
    ]
