# Generated by Django 5.2.1 on 2025-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pricemodel_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='adult',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Adult Price'),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='child',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Child Price'),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='student',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Student Price'),
        ),
        migrations.DeleteModel(
            name='PriceModel',
        ),
    ]
