# Generated by Django 5.2.1 on 2025-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ticketmodel_price_sessionmodel_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='time',
            field=models.DateTimeField(verbose_name='Time'),
        ),
    ]
